### ISSUE TITLE
Improve contribution guidance

### ISSUE THREAD

**Issue by thomasgouveia** [rik-org/rik#40]
We need to improve our project by setting up some contributions guidelines.

I think we should add at least : 

- Issues templates
- Define the commits pattern
- How to run & build the project locally (as for now, ideally for macOS, Ubuntu and Fedora) (docker, scripts ....)

**Comment by hugoamalric** [comment]
To keep you updated about the progress : 
- [ ] Issues|Pull request templates : Fixed in #48 
- [ ] How to run & build the project locally : Fixed in #28
- [ ] Define the commits pattern, PR workflow (contributing guide) :  WIP in

**Comment by AlexandreBrg** [comment]
Commit pattern and the PR workflow has been added through https://github.com/rik-org/rik/commit/92a1d6a4ff0b31704d2267032e9ef244d6739858 by @hugoamalric 

Thank you guys
